(()=>{
  'use strict';
  const cfg=window.DEREJ_CONFIG||{},BASE=String(cfg.supabaseUrl||'').replace(/\/$/,''),KEY=cfg.supabasePublishableKey||'';
  const FUNCTIONS={testimony:cfg.moderationFunction||'moderation-console',fruit:cfg.fruitModerationFunction||'fruit-moderation-console'};
  const SESSION_KEY='derej:moderator:session:v1',$=id=>document.getElementById(id);
  const state={status:'pending',resource:'testimony',session:null,role:null};
  function headers(token=null,json=false){const h={apikey:KEY};if(token)h.Authorization=`Bearer ${token}`;if(json)h['Content-Type']='application/json';return h}
  function readSession(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
  function saveSession(raw){const s={access_token:raw.access_token,refresh_token:raw.refresh_token,expires_at:raw.expires_at||Math.floor(Date.now()/1000)+(raw.expires_in||3600)};sessionStorage.setItem(SESSION_KEY,JSON.stringify(s));state.session=s;return s}
  function clearSession(){sessionStorage.removeItem(SESSION_KEY);state.session=null;state.role=null}
  function valid(s){return Boolean(s?.access_token&&Number(s.expires_at)>Math.floor(Date.now()/1000)+90)}
  async function auth(path,body){const res=await fetch(`${BASE}/auth/v1/${path}`,{method:'POST',headers:headers(null,true),body:JSON.stringify(body)}),data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error_description||data.msg||data.error||`Auth ${res.status}`);return data}
  async function ensureSession(){let s=state.session||readSession();if(valid(s)){state.session=s;return s}if(s?.refresh_token){try{return saveSession(await auth('token?grant_type=refresh_token',{refresh_token:s.refresh_token}))}catch{clearSession()}}throw new Error('session_required')}
  async function api(method='GET',body=null,status=state.status){const s=await ensureSession(),url=new URL(`${BASE}/functions/v1/${FUNCTIONS[state.resource]}`);if(method==='GET'){url.searchParams.set('status',status);url.searchParams.set('limit','100')}const res=await fetch(url,{method,headers:headers(s.access_token,Boolean(body)),body:body?JSON.stringify(body):undefined}),data=await res.json().catch(()=>({}));if(res.status===401||res.status===403){if(['invalid_session','authentication_required'].includes(data.error))clearSession();throw new Error(data.error||`HTTP ${res.status}`)}if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);return data}
  function showLogin(message=''){$('modLogin').hidden=false;$('modConsole').hidden=true;$('modLogout').hidden=true;$('modLoginStatus').textContent=message}
  function showConsole(){$('modLogin').hidden=true;$('modConsole').hidden=false;$('modLogout').hidden=false}
  function fmtDate(v){try{return new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return v||''}}
  function titleFor(){const s=state.status==='pending'?'Pendientes':state.status==='published'?'Publicados':'Ocultos';return `${state.resource==='fruit'?'Frutos':'Testimonios'} · ${s}`}
  function errorText(err){const map={moderator_access_required:'Esta cuenta existe, pero no está autorizada como moderador.',permanent_account_required:'Las identidades anónimas no pueden moderar.',invalid_session:'La sesión expiró. Ingresa nuevamente.',authentication_required:'Debes iniciar sesión.',queue_load_failed:'No fue posible cargar la cola.',moderation_update_failed:'No fue posible guardar la decisión.',invalid_public_body:'El texto público del fruto debe tener entre 20 y 1.200 caracteres.'};return map[err.message]||err.message||'No fue posible completar la acción.'}
  function field(tag,cls,value=''){const n=document.createElement(tag);n.className=cls;n.value=value||'';return n}
  function render(items){const box=$('modQueue');box.replaceChildren();if(!items.length){const e=document.createElement('div');e.className='emptyState';e.textContent=`No hay ${state.resource==='fruit'?'frutos':'testimonios'} en este estado.`;box.append(e);return}items.forEach(item=>box.append(state.resource==='fruit'?renderFruit(item):renderTestimony(item)))}
  function baseCard(item,label){const card=document.createElement('article');card.className=`moderatorItem ${item.moderation_level||'green'}`;card.dataset.id=item.id;const head=document.createElement('div');head.className='moderatorItemHead';const left=document.createElement('div'),ey=document.createElement('div');ey.className='eyebrow';ey.textContent=label;const lv=document.createElement('div');lv.className='moderatorLevel';lv.textContent=`${(item.moderation_level||'green').toUpperCase()} · ${item.status}`;left.append(ey,lv);const time=document.createElement('div');time.className='moderatorTimestamp';time.textContent=fmtDate(item.created_at);head.append(left,time);card.append(head);return card}
  function appendFlags(card,item){const flags=document.createElement('div');flags.className='moderatorFlags';(item.moderation_flags||[]).forEach(f=>{const x=document.createElement('span');x.className='moderatorFlag';x.textContent=f;flags.append(x)});if(flags.childNodes.length)card.append(flags);if(item.moderation_note){const p=document.createElement('p');p.className='small';p.textContent=`Señal automática: ${item.moderation_note}`;card.append(p)}}
  function noteField(card,item){const label=document.createElement('label');label.className='moderatorNoteLabel';label.textContent='Nota interna de revisión';const note=document.createElement('textarea');note.className='moderatorNote';note.rows=2;note.maxLength=1000;note.value=item.moderator_note||'';label.append(note);card.append(label);return note}
  function renderTestimony(item){const card=baseCard(item,item.conversation?.title||item.conversation?.slug||'Conversación'),body=document.createElement('div');body.className='moderatorBodyText';body.textContent=item.body;card.append(body);appendFlags(card,item);if(item.reports?.open_count){const r=document.createElement('div');r.className='moderatorReports';r.innerHTML=`<strong>${item.reports.open_count} reporte(s) abierto(s)</strong>`;(item.reports.items||[]).forEach(x=>{const row=document.createElement('div');row.className='moderatorReport';row.textContent=`${x.reason}${x.details?' · '+x.details:''}`;r.append(row)});card.append(r)}const note=noteField(card,item),actions=document.createElement('div');actions.className='moderatorActions';if(item.status!=='published')actions.append(actionBtn('Publicar','publish',card,note));if(item.status!=='hidden')actions.append(actionBtn('Ocultar','hide',card,note,true));if(item.status!=='pending')actions.append(actionBtn('Volver a pendiente','return_pending',card,note));if(item.status==='published'&&item.reports?.open_count)actions.append(actionBtn('Mantener publicado · cerrar reportes','dismiss_reports',card,note));card.append(actions);return card}
  function renderFruit(item){const card=baseCard(item,item.origin_title||'Fruto Dérej'),origin=document.createElement('div');origin.className='moderatorOrigin';origin.textContent=`${item.origin_type} · ${item.origin_ref}${item.experienced_on?' · vivido '+item.experienced_on:''}`;card.append(origin);const original=document.createElement('div');original.className='moderatorBodyText';original.textContent=item.body;card.append(original);appendFlags(card,item);const editorial=document.createElement('div');editorial.className='moderatorEditorial';const lt=document.createElement('label');lt.textContent='Título público';const title=field('input','',item.public_title||'Un fruto del camino');title.maxLength=140;lt.append(title);const lb=document.createElement('label');lb.textContent='Versión pública anónima';const pub=field('textarea','',item.public_body||item.body);pub.rows=5;pub.maxLength=1200;lb.append(pub);const lg=document.createElement('label');lg.textContent='Etiquetas · separadas por coma';const tg=field('input','moderatorTagsInput',(item.tags||[]).join(', '));lg.append(tg);editorial.append(lt,lb,lg);card.append(editorial);const note=noteField(card,item),actions=document.createElement('div');actions.className='moderatorActions';const payload=()=>({public_title:title.value.trim(),public_body:pub.value.trim(),tags:tg.value.split(',').map(x=>x.trim()).filter(Boolean)});if(item.status!=='published')actions.append(actionBtn('Publicar fruto','publish',card,note,false,payload));if(item.status==='published')actions.append(actionBtn('Guardar edición pública','edit_public',card,note,false,payload));if(item.status!=='hidden')actions.append(actionBtn('Ocultar','hide',card,note,true));if(item.status!=='pending')actions.append(actionBtn('Volver a pendiente','return_pending',card,note));card.append(actions);return card}
  function actionBtn(label,action,card,note,danger=false,extra=null){const b=document.createElement('button');b.type='button';b.textContent=label;b.className=danger?'dangerBtn':'secondaryBtn';b.addEventListener('click',async()=>{card.setAttribute('aria-busy','true');$('modStatus').textContent='Guardando decisión…';try{let body=state.resource==='fruit'?{fruit_id:card.dataset.id,action,note:note.value.trim()||null}:{testimony_id:card.dataset.id,action,note:note.value.trim()||null};if(extra)body={...body,...extra()};await api('POST',body);$('modStatus').textContent='Decisión guardada y auditada ✓';await loadQueue()}catch(e){$('modStatus').textContent=errorText(e)}finally{card.removeAttribute('aria-busy')}});return b}
  async function loadQueue(){$('modQueueTitle').textContent=titleFor();$('modStatus').textContent='Cargando…';try{const data=await api('GET',null,state.status);state.role=data.moderator?.role||'moderator';$('modRole').textContent=`Rol: ${state.role}`;render(data.items||[]);$('modStatus').textContent=`${data.count||0} ${state.resource==='fruit'?'fruto(s)':'testimonio(s)'} · datos no almacenados en caché local.`;showConsole()}catch(e){if(['session_required','invalid_session','authentication_required','moderator_access_required','permanent_account_required'].includes(e.message))showLogin(errorText(e));else $('modStatus').textContent=errorText(e)}}
  $('modLoginForm').addEventListener('submit',async e=>{e.preventDefault();$('modLoginStatus').textContent='Verificando acceso…';try{const data=await auth('token?grant_type=password',{email:$('modEmail').value.trim(),password:$('modPassword').value});saveSession(data);$('modPassword').value='';await loadQueue()}catch(err){clearSession();showLogin(errorText(err))}});
  $('modLogout').addEventListener('click',()=>{clearSession();$('modQueue').replaceChildren();showLogin('Sesión cerrada en este dispositivo.')});$('modRefresh').addEventListener('click',loadQueue);
  document.querySelectorAll('[data-status]').forEach(btn=>btn.addEventListener('click',()=>{state.status=btn.dataset.status;document.querySelectorAll('[data-status]').forEach(x=>x.classList.toggle('on',x===btn));loadQueue()}));
  document.querySelectorAll('[data-resource]').forEach(btn=>btn.addEventListener('click',()=>{state.resource=btn.dataset.resource;state.status='pending';document.querySelectorAll('[data-resource]').forEach(x=>x.classList.toggle('on',x===btn));document.querySelectorAll('[data-status]').forEach(x=>x.classList.toggle('on',x.dataset.status==='pending'));loadQueue()}));
  if(!BASE||!KEY){showLogin('Configuración de Supabase incompleta.')}else{state.session=readSession();if(valid(state.session)||state.session?.refresh_token)loadQueue();else showLogin()}
})();
